name: build_filesystem
version: 1.0.0
description: A `package:file` implementation for use in builders and code generators.
author: Tobe Osakwe <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/build_filesystem
environment:
 sdk: ">=2.0.0 <3.0.0"
dependencies:
  build: ^1.0.0
  file: ^5.0.0
  glob: ^1.0.0
  path: ^1.0.0
  scratch_space: ^0.0.4
dev_dependencies:
  build_test: ^0.10.0
  pedantic: ^1.0.0
  test: ^1.0.0